[package]
name = "lazyactions"
version = "0.1.0"
description = "tui to view github actions"
authors = ["Ben <ben.farrington@nisien.ai>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
serde_json = "1.0.140"
serde = { version = "1", features = ["derive"] }
